apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}-${SLOT}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
      version: ${SLOT}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        version: ${SLOT}
    spec:
      containers:
        - name: api
          image: ${IMAGE}
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /ruta-falsa
              port: 3000
            initialDelaySeconds: 5
