on: [push]                      # Trigger: cualquier push a cualquier rama

jobs:
  mi-job:
    # Cambia TU_USUARIO_AQUI por tu usuario de GitHub. 
    # Usaremos @main asumiendo que ahí guardaste tu workflow proveedor.
    uses: gat0hub/AUY1104Pipelines/.github/workflows/deploy-api.yaml@main
    with:
      image-name: "algo"
      image-tag: ${{ github.sha }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Del repo SharedClient
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Del repo SharedClient
