name: Release Pipeline

on: 
  push:
    tags:
      - 'v*.*.*'  # Trigger: SOLO se ejecuta cuando creas un tag

jobs:
  mi-job:
    uses: gat0hub/AUY1104Pipelines/.github/workflows/deploy-api.yaml@main
    with:
      image-name: "imagen-docker"
      image-tag: ${{ github.ref_name }} # Extrae el nombre del tag automáticamente
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
