on:
  push:
    tags:
    - 'v*.*.*'                # Trigger: cualquier push a cualquier ramaaaaaa

jobs:
  usar-receta-compartida:
    uses: gat0hub/AUY1104Pipelines/.github/workflows/deploy-api.yaml@main
    with:
      image-name: "primo-de-algo"
      image-tag: ${{ github.ref_name }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Del repo SharedClient
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Del repo SharedClient
#hola